### ISSUE TITLE
Feature request:  use not? conditional operation on self question ID

### ISSUE THREAD

**Issue by adberard** [isobar-us/redux-form-gen#32]
Hello,
I have this use case I would need that the question disapear after being answered (Because its a suit of questions and I lack of place).
I tryed to use the conditional visible operator but it cannot be used on the same component.
I also tryed to put the condition in a wrapping group above the field but with the same result.

https://codesandbox.io/s/9pkoo422o

**Comment by bmv437** [comment]
Hey @adberard,

I see what you mean in the example you provided. Here are my thoughts:

* Making a field hidden using `conditionalVisible` will hide the field, and also clear that field's value from the form data. I have a feeling this is what is causing the infinite loop to occur. field filled => field hidden => field value cleared => field visible => field value restored => field filled => back to beginning.
* If you hide a field once it's answered, then the user has no way to change their answer, which would lead to a confusing user experience.
* My suggestion would be to use a Wizard form pattern if you're tight on screen space. This would allow the user to navigate to a previous step if they want to change their answers before submitting the form.

Let me know if that makes sense.
Thanks!

**Comment by adberard** [comment]
Okay I get it, I didn't wanted to recreate a wrapping custom component again but it seem to be the legit solution.
